### ISSUE TITLE
Tool tip fix

### ISSUE THREAD

**Issue by joeybagofdonuts** [sgkoishi/PackTracker#12]
![image](https://user-images.githubusercontent.com/2894812/133495001-689e86de-0c52-435d-a86b-6a5327ef29f6.png)

Any way to fix this?

**Comment by sgkoishi** [comment]
It seems to be the colour schema problem - hopefully it would be a quick fix.

**Comment by joeybagofdonuts** [comment]
Looks great!  Thanks!
