### ISSUE TITLE
Manual Add

### ISSUE THREAD

**Issue by joeybagofdonuts** [sgkoishi/PackTracker#17]
Very happy to see this feature, however, tried to add a standard pack today and the dropdown list of cards is empty after picking Standard.

**Comment by sgkoishi** [comment]
Duplicate of #15 
Fixed for next release. You may download the nightly version from [here](https://github.com/sgkoishi/PackTracker/actions); click the topmost one and download the `Artifact` inside. A note that standard, golden standard and wild packs may contain different cards during different periods, so the range of them was set to any card (not only standard or wild)
