### ISSUE TITLE
Pity timer overlay not working with HDT 1.16.7

### ISSUE THREAD

**Issue by AntonK89** [sgkoishi/PackTracker#18]
PackTracker doesn't show the overlay while opening packs after the HDT update. Tracking is working.

Related log messages:

> 3:38:23 AM|Info|GameV2.CurrentMode >> PACKOPENING
> 3:38:24 AM|Info|CollectionHelper.UpdateCollection >> Updated collection!
> 3:38:27 AM|Info|PackUploader.UploadPack >> New Pack! Id=632, Cards=[BT_026, SW_049, YOP_011, DMF_194, BAR_881]
> 3:38:40 AM|Warning|Core.Initialize >> HearthMirror Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
>    at CallSite.Target(Closure , CallSite , Object , String )
>    at HearthMirror.Reflection.<GetPackCardsInternal>d__84.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at HearthMirror.Reflection.<>c.<GetPackCards>b__83_0()
>    at HearthMirror.Reflection.TryGetInternal[T](Func`1 action, Boolean clearCache)

Probably has something to do with [this large commit](https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/4ff343930e19709d2b0eb4a0f0f71dc13a27870a).

**Comment by sgkoishi** [comment]
You are right. It seems that the handler was removed by the null checking, which I am not sure if I did wrong or this is a bug. The workaround should be quick tho :)

**Comment by sgkoishi** [comment]
Fixed by dbe090f84cc4452aa0036a0a8940ed4251975496, [released](https://github.com/sgkoishi/PackTracker/releases/tag/v1.4.11).

**Comment by formigao** [comment]
Overlay is still broken version 1.4.12
