### ISSUE TITLE
Error when building the fork

### ISSUE THREAD

**Issue by TheMrKochan** [sgkoishi/PackTracker#21]
When translating your fork, it gives an error that the parameter is outdated (sorry, the screenshot is in Russian). I tried to install HearthDB from version 1.16.8-1.16.10, but it didn't help and as a result, this error does not allow the release to assemble
![nt](https://user-images.githubusercontent.com/75619070/144879118-fad5b194-fa66-4920-a66a-9b6524fbd899.jpg)
.

**Comment by TheMrKochan** [comment]
Thx!

**Comment by sgkoishi** [comment]
It seems to be a part of HDT itself instead of HearthDB. Switch back to previous HDT should still be able to build and run but it's just one line so hopefully an easy fix :)
