### ISSUE TITLE
Pulled a golden legendary, was counted as Epic and legendary timer did not reset.

### ISSUE THREAD

**Issue by mcbexx** [sgkoishi/PackTracker#22]
Got the golden legendary 4 packs ago. Epic counter went down to zero, legendary still at 9 (see screenshots of log and pity timer bars
![NVIDIA_Share_q72qxQo3H4](https://user-images.githubusercontent.com/56156474/145091661-6ea350b7-a0e7-4b9e-bdf8-8c7b3ada2fa5.png)
![HearthstoneDeckTracker_xsxpzIk0Hg](https://user-images.githubusercontent.com/56156474/145091667-ad59af93-9150-4a0f-b0f7-ce3fcd5b5439.png)
).

**Comment by sgkoishi** [comment]
It is expected. Golden legends do not reset legend pity timer, you still expect another *non-golden* legend before the pity timer reaches 40.
This may be unintuitive, but there is an option that allows you to set "golden card reset regular pity timer".

See https://github.com/MGK82/PackTracker/issues/35
