### ISSUE TITLE
The "Log" feature responses laggy when you have history with many packs

### ISSUE THREAD

**Issue by Westwoodmayim** [sgkoishi/PackTracker#24]
As described, it's hard to use this feature because with very slow response

**Comment by sgkoishi** [comment]
Yes, but I actually have no idea what to do with this feature. Probably it would be better to show plain text instead of coloured, or show last 20 and load as mouse scrolls
~~Does anyone use this feature?~~

**Comment by Westwoodmayim** [comment]
> Yes, but I actually have no idea what to do with this feature. Probably it would be better to show plain text instead of coloured, or show last 20 and load as mouse scrolls ~Does anyone use this feature?~

hmmm maybe export it as a html ( or other rich text format ) file ( to avoid HDT built-in framework ) is eithor ok ?
( or just plain text with a bit more "highest rarity" info ? )

**Comment by Westwoodmayim** [comment]
> Yes, but I actually have no idea what to do with this feature. Probably it would be better to show plain text instead of coloured, or show last 20 and load as mouse scrolls ~Does anyone use this feature?~

or just some function like "Copy to clickboard" ? so the content can be viewed and processed via other methods

**Comment by sgkoishi** [comment]
> Feature: While the Log window is opened, press Ctrl+C to copy the log and Ctrl+S to save a CSV spreadsheet.

Since 1.4.9 ~~but yes you still have to wait for it to load first🤣~~

**Comment by Westwoodmayim** [comment]
> > Feature: While the Log window is opened, press Ctrl+C to copy the log and Ctrl+S to save a CSV spreadsheet.
> 
> Since 1.4.9 ~but yes you still have to wait for it to load first🤣~

OHHHHH my bad... i tried all best to select it first by never just go Ctrl+C first...
