### ISSUE TITLE
Move/resize pity timer overlay

### ISSUE THREAD

**Issue by Californ1a** [sgkoishi/PackTracker#26]
I have 3 monitors and play with HS borderless windowed on my center monitor, but the pity timer overlay shows up all the way on the far right side of my right monitor with no way to move it.

![](https://i.imgur.com/YmurnCi.png)

**Comment by sgkoishi** [comment]
Tbh, I have no idea how multiple monitors work nor any resource to test it 😂 
Probably could have a button to switch between monitors but had to deal with scaling, or have some hidden config file option to manually specify XY coordinate

**Comment by Californ1a** [comment]
Having a lock/unlock and a way to drag it around when it's unlocked like the main deck list overlays in HDT would be ideal.

**Comment by sgkoishi** [comment]
Make sense ~~but can't work on it for now - probably one or two weeks later~~

**Comment by sgkoishi** [comment]
I've added an option to switch between HS window/rightmost of the screen and is enabled (rightmost) by default. Would you like to try [it](https://github.com/sgkoishi/PackTracker/actions/runs/2145263305)?

_(or just click the [Artifact](https://github.com/sgkoishi/PackTracker/suites/6066638880/artifacts/209627319) to download)_

**Comment by Californ1a** [comment]
Seems like two options are on top of each other:
![](https://i.imgur.com/aIB2OtN.png)

With the overlay enabled and the bottom one disabled ([as such](https://i.imgur.com/alfjlQ7.png)), the overlay is outside the HS window to the top left:
![](https://i.imgur.com/BF2JGFG.png)

**Comment by sgkoishi** [comment]
Seems AI is still not clever enough lol... How about the [latest one](https://github.com/sgkoishi/PackTracker/actions/runs/2146509168)?

**Comment by Californ1a** [comment]
Now it's in the bottom right corner:
![](https://i.imgur.com/8l6PT9l.png)

**Comment by sgkoishi** [comment]
Hopefully [this one](https://github.com/sgkoishi/PackTracker/actions/runs/2147150568) I guess?

**Comment by Californ1a** [comment]
Much closer. It is slightly off the right side of the HS window:
![](https://i.imgur.com/nK6Z9Z7.png)
