### ISSUE TITLE
Show IDs. Hide sets with no data

### ISSUE THREAD

**Issue by q1k** [sgkoishi/PackTracker#35]
- I'd like to hide all the sets where there's no info (haven't opened any packs or pity timers are at zero),
- quick setting to only show standard, wild, or all sets
- and also show the IDs of the sets, either in brackets or before the name of the set

Also, why are there two Classic sets?

**Comment by sgkoishi** [comment]
- I'd like to hide all the sets where there's no info (haven't opened any packs or pity timers are at zero),
  - There is already an option for that. Turn off the `Show Untracked`, or try the latest CI version.
- quick setting to only show standard, wild, or all sets
  - Seems a lot of work and not planned - no idea how to work with WPF
- and also show the IDs of the sets, either in brackets or before the name of the set
  - Done in CI version.
- Also, why are there two Classic sets?
  - Those data were obtained from the game itself, I don't know why they have two packs for same content.

[Latest CI version](https://github.com/sgkoishi/PackTracker/actions) removes the `Show Untracked` option, and hide packs if this account has never opened it and the tracker has never tracked it, and show the numerical pack type (id).
