### ISSUE TITLE
Manual add standard pack will frozen/crash

### ISSUE THREAD

**Issue by DavidMatson47** [sgkoishi/PackTracker#38]
I open a standard pack at hearthstone, but It has crashed. so I try manually add the result of it, but It keeps frozen or crash. 
![38](https://github.com/sgkoishi/PackTracker/assets/103190834/9073d0e7-5a3c-45a6-98fc-c63018839728)

**Comment by sgkoishi** [comment]
Could you try to restart the deck tracker and see if it can track packs?

For manual add, fixed for next release, or you can download the nightly version [here](https://github.com/sgkoishi/PackTracker/actions).
