### ISSUE TITLE
"Show the overall amount of packs you've ever got" not working

### ISSUE THREAD

**Issue by hetchel** [sgkoishi/PackTracker#40]
I have HS open, It's synchronizing ok with the rest of HDT, but can see the history of untracked packs in "Statistics". Tried restarting both HDT and HS, no result.
All the rest of the features seem to work ok. The overlay is showing in HS, tracked packs statistics do show, etc.
I'm updated to the last version of everything.

**Comment by sgkoishi** [comment]
Can you take a screenshot of it?

**Comment by hetchel** [comment]
Will do, but will take a few hours.

________________________________

**Comment by sgkoishi** [comment]
Confirmed, caused by the internal change of HDT. Fixed for next release.
