### ISSUE TITLE
update for the new expasion

### ISSUE THREAD

**Issue by formigao** [sgkoishi/PackTracker#54]

**Comment by sgkoishi** [comment]
You can try the latest version here, https://github.com/sgkoishi/PackTracker/actions. Haven't tested so not released yet but probably works

**Comment by formigao** [comment]
> You can try the latest version here, https://github.com/sgkoishi/PackTracker/actions. Haven't tested so not released yet but probably works

how you do that?

**Comment by sgkoishi** [comment]
Click the first one and you should see a section named Artifacts and that's it

**Comment by dpsi** [comment]
For anyone reading this issue, you need to be signed into GitHub to download it from the CI.
